const mongoose = require("mongoose")
const orderSchema = mongoose.Schema({
    username:{
        type:String,
        required:true
    },
    userId:{
        type:mongoose.Types.ObjectId,
        required:true
    },
    phoneNo:{
        type:Number,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    totalPaidAmount:{
        type:Number,
        required:true
    },
    status:{
        type:String,
        requried:true,
        enum:["Processing","Confirmed","Shipped","Out For Delivery","Delivered","Cancelled","Refund"],
        default:"Processing"
    },
    item:[
        {
            
            productId:{
                type:String,
                requried:true
            },
            name:{
                type:String,
                required:true
            },
            thumbnail:{
                type:String,
                required:true
            },
            size:{
                type:String
            },
            color:{
                type:String,
            },
            price:{
                type:Number,
                required:true
            },
            qty:{
                type:Number,
                required:true
            },
            deliveryCharge:{
                type:String,
                required:true
            },
            GST:{
                type:String,
                requried:true
            }
        }
    ],
    razorpay_payment_id:{
        type:String,
        requried:true
    },
    razorpay_order_id:{
        type:String,
        required:true
    },
    createdAt:{
        type:Date,
        default:Date.now(),
        required:true
    }
})

module.exports = mongoose.model("order",orderSchema)